{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1dc6cda6-d58d-43a8-83bb-5bb7343214fa",
   "metadata": {},
   "source": [
    "Section 1 — Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "32ab1b05-ca15-4172-be12-7154c758964d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Employee Performance Analysis\n",
    "# Modeling Framework\n",
    "# ==========================================================\n",
    "\n",
    "import os\n",
    "import time\n",
    "import warnings\n",
    "import joblib\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "warnings.filterwarnings(\"ignore\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "937fd89f-0d24-403a-823e-f1ee6591f118",
   "metadata": {},
   "source": [
    "Section 2 — Sklearn Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "3051a53c-3d21-4cdd-86cc-0007bd611cd5",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import (\n",
    "\n",
    "    accuracy_score,\n",
    "    balanced_accuracy_score,\n",
    "    precision_score,\n",
    "    recall_score,\n",
    "    f1_score,\n",
    "    roc_auc_score,\n",
    "    confusion_matrix,\n",
    "    classification_report\n",
    "\n",
    ")\n",
    "\n",
    "from sklearn.model_selection import cross_val_score\n",
    "\n",
    "from sklearn.preprocessing import label_binarize"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0bd72d84-7162-4284-91d5-3fd4f7569937",
   "metadata": {},
   "source": [
    "Section 3 — Experiment Columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "4e510a7a-1c6c-485d-b537-b40d672b475e",
   "metadata": {},
   "outputs": [],
   "source": [
    "RESULT_COLUMNS = [\n",
    "\n",
    "    \"Model\",\n",
    "\n",
    "    \"Accuracy\",\n",
    "\n",
    "    \"Balanced Accuracy\",\n",
    "\n",
    "    \"Precision\",\n",
    "\n",
    "    \"Recall\",\n",
    "\n",
    "    \"F1 Score\",\n",
    "\n",
    "    \"ROC-AUC\",\n",
    "\n",
    "    \"CV Mean\",\n",
    "\n",
    "    \"CV Std\",\n",
    "\n",
    "    \"Training Time\",\n",
    "\n",
    "    \"Prediction Time\",\n",
    "\n",
    "    \"Status\"\n",
    "\n",
    "]"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dfc6b21f-9262-4703-83e4-4d0017704ce1",
   "metadata": {},
   "source": [
    "Section 4 Folder Creation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "ca7b76d7-d7f2-49db-b553-938eddd6523a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_project_folders(\n",
    "\n",
    "    models_dir,\n",
    "\n",
    "    results_dir\n",
    "\n",
    "):\n",
    "\n",
    "    folders = {\n",
    "\n",
    "        \"trained_models\":\n",
    "            os.path.join(models_dir,\"trained_models\"),\n",
    "\n",
    "        \"best_model\":\n",
    "            os.path.join(models_dir,\"best_model\"),\n",
    "\n",
    "        \"scalers\":\n",
    "            os.path.join(models_dir,\"scalers\"),\n",
    "\n",
    "        \"reports\":\n",
    "            os.path.join(results_dir,\"reports\"),\n",
    "\n",
    "        \"confusion_matrices\":\n",
    "            os.path.join(results_dir,\"confusion_matrices\"),\n",
    "\n",
    "        \"roc_curves\":\n",
    "            os.path.join(results_dir,\"roc_curves\"),\n",
    "\n",
    "        \"cross_validation\":\n",
    "            os.path.join(results_dir,\"cross_validation\"),\n",
    "\n",
    "        \"predictions\":\n",
    "            os.path.join(results_dir,\"predictions\"),\n",
    "\n",
    "        \"feature_importance\":\n",
    "            os.path.join(results_dir,\"feature_importance\")\n",
    "\n",
    "    }\n",
    "\n",
    "    for folder in folders.values():\n",
    "\n",
    "        os.makedirs(\n",
    "\n",
    "            folder,\n",
    "\n",
    "            exist_ok=True\n",
    "\n",
    "        )\n",
    "\n",
    "    return folders"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6f986e6b-9bb2-44c4-ba5d-c6bf5196f912",
   "metadata": {},
   "source": [
    "Section 5 Initialize Experiment"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "4d4028c1-2bac-4bae-987a-704d2e14a68a",
   "metadata": {},
   "outputs": [],
   "source": [
    "def initialize_experiment(\n",
    "\n",
    "    report_folder\n",
    "\n",
    "):\n",
    "\n",
    "    result_file = os.path.join(\n",
    "\n",
    "        report_folder,\n",
    "\n",
    "        \"Model_Comparison.csv\"\n",
    "\n",
    "    )\n",
    "\n",
    "    if os.path.exists(result_file):\n",
    "\n",
    "        results = pd.read_csv(result_file)\n",
    "\n",
    "    else:\n",
    "\n",
    "        results = pd.DataFrame(\n",
    "\n",
    "            columns=RESULT_COLUMNS\n",
    "\n",
    "        )\n",
    "\n",
    "        results.to_csv(\n",
    "\n",
    "            result_file,\n",
    "\n",
    "            index=False\n",
    "\n",
    "        )\n",
    "\n",
    "    return results, result_file"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1befca9b-5c38-462a-8a87-418c0cc9c1aa",
   "metadata": {},
   "source": [
    "Section 6 Crash Recovery"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "333ecd29-1367-4a1b-aa80-038fcfec39be",
   "metadata": {},
   "outputs": [],
   "source": [
    "def is_completed(\n",
    "\n",
    "    model_name,\n",
    "\n",
    "    results_df\n",
    "\n",
    "):\n",
    "\n",
    "    if len(results_df)==0:\n",
    "\n",
    "        return False\n",
    "\n",
    "    row = results_df[\n",
    "\n",
    "        results_df[\"Model\"]==model_name\n",
    "\n",
    "    ]\n",
    "\n",
    "    if len(row)==0:\n",
    "\n",
    "        return False\n",
    "\n",
    "    return row.iloc[0][\"Status\"]==\"Completed\""
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f6ce54d6-7d4d-4b41-9408-49354c3e6736",
   "metadata": {},
   "source": [
    "Step 2 – Saving Utilities"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "d13ff924-b5f4-4b5d-8215-b5f9c808c30b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Save Trained Model\n",
    "# ==========================================================\n",
    "\n",
    "def save_model(\n",
    "    model,\n",
    "    model_name,\n",
    "    model_folder\n",
    "):\n",
    "    \"\"\"\n",
    "    Save trained machine learning model.\n",
    "    \"\"\"\n",
    "\n",
    "    filename = model_name.replace(\" \", \"_\") + \".pkl\"\n",
    "\n",
    "    filepath = os.path.join(\n",
    "        model_folder,\n",
    "        filename\n",
    "    )\n",
    "\n",
    "    joblib.dump(model, filepath)\n",
    "\n",
    "    return filepath"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "210656a5-35dd-43f5-8e9a-a1ddc034258c",
   "metadata": {},
   "source": [
    "Section 8 – Save Scaler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "bbaea0e0-e3f7-4705-8d23-b1fe4eabe642",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Save StandardScaler\n",
    "# ==========================================================\n",
    "\n",
    "def save_scaler(\n",
    "    scaler,\n",
    "    scaler_folder\n",
    "):\n",
    "    \"\"\"\n",
    "    Save fitted StandardScaler.\n",
    "    \"\"\"\n",
    "\n",
    "    filepath = os.path.join(\n",
    "        scaler_folder,\n",
    "        \"StandardScaler.pkl\"\n",
    "    )\n",
    "\n",
    "    joblib.dump(\n",
    "        scaler,\n",
    "        filepath\n",
    "    )\n",
    "\n",
    "    return filepath"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "67bcb731-bc9c-40ac-a2e1-a7c5d5382c7c",
   "metadata": {},
   "source": [
    "Section 9 – Save Classification Report"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "68603ef0-69b7-4971-a1fc-52fb20fbf980",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Save Classification Report\n",
    "# ==========================================================\n",
    "\n",
    "def save_classification_report(\n",
    "    y_true,\n",
    "    y_pred,\n",
    "    report_folder,\n",
    "    model_name\n",
    "):\n",
    "    \"\"\"\n",
    "    Save classification report as CSV.\n",
    "    \"\"\"\n",
    "\n",
    "    report = classification_report(\n",
    "        y_true,\n",
    "        y_pred,\n",
    "        output_dict=True\n",
    "    )\n",
    "\n",
    "    report_df = pd.DataFrame(report).transpose()\n",
    "\n",
    "    filepath = os.path.join(\n",
    "\n",
    "        report_folder,\n",
    "\n",
    "        model_name.replace(\" \", \"_\")\n",
    "\n",
    "        + \"_Classification_Report.csv\"\n",
    "\n",
    "    )\n",
    "\n",
    "    report_df.to_csv(\n",
    "        filepath\n",
    "    )\n",
    "\n",
    "    return filepath"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e75835ee-3f93-4228-be94-858ef6653ffe",
   "metadata": {},
   "source": [
    "Section 10 – Save Predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "68dfaf2e-c9b1-4944-ab8a-3cc400719d6a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Save Predictions\n",
    "# ==========================================================\n",
    "\n",
    "def save_predictions(\n",
    "    y_true,\n",
    "    y_pred,\n",
    "    prediction_folder,\n",
    "    model_name\n",
    "):\n",
    "    \"\"\"\n",
    "    Save actual vs predicted values.\n",
    "    \"\"\"\n",
    "\n",
    "    prediction_df = pd.DataFrame({\n",
    "\n",
    "        \"Actual\": y_true,\n",
    "\n",
    "        \"Predicted\": y_pred\n",
    "\n",
    "    })\n",
    "\n",
    "    filepath = os.path.join(\n",
    "\n",
    "        prediction_folder,\n",
    "\n",
    "        model_name.replace(\" \", \"_\")\n",
    "\n",
    "        + \"_Predictions.csv\"\n",
    "\n",
    "    )\n",
    "\n",
    "    prediction_df.to_csv(\n",
    "\n",
    "        filepath,\n",
    "\n",
    "        index=False\n",
    "\n",
    "    )\n",
    "\n",
    "    return filepath"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d9108c92-2e4b-4910-9f37-0469abaa45d5",
   "metadata": {},
   "source": [
    "Section 11 – Save Cross Validation Scores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "279f05fa-5043-4b54-8c5b-619f177c9cec",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Save Cross Validation Scores\n",
    "# ==========================================================\n",
    "\n",
    "def save_cv_scores(\n",
    "    scores,\n",
    "    cv_folder,\n",
    "    model_name\n",
    "):\n",
    "    \"\"\"\n",
    "    Save cross-validation fold scores.\n",
    "    \"\"\"\n",
    "\n",
    "    cv_df = pd.DataFrame({\n",
    "\n",
    "        \"Fold\": np.arange(1, len(scores)+1),\n",
    "\n",
    "        \"Score\": scores\n",
    "\n",
    "    })\n",
    "\n",
    "    filepath = os.path.join(\n",
    "\n",
    "        cv_folder,\n",
    "\n",
    "        model_name.replace(\" \", \"_\")\n",
    "\n",
    "        + \"_CV_Scores.csv\"\n",
    "\n",
    "    )\n",
    "\n",
    "    cv_df.to_csv(\n",
    "\n",
    "        filepath,\n",
    "\n",
    "        index=False\n",
    "\n",
    "    )\n",
    "\n",
    "    return filepath"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6154be35-b1d4-498f-a20c-45f0b8e537c1",
   "metadata": {},
   "source": [
    "Section 12 – Update Results Table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "2dede623-c2b7-4551-ab0f-8483fa93ec79",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Update Master Results Table\n",
    "# ==========================================================\n",
    "\n",
    "def update_results_table(\n",
    "    results_df,\n",
    "    result,\n",
    "    result_file\n",
    "):\n",
    "    \"\"\"\n",
    "    Append model result and save.\n",
    "    \"\"\"\n",
    "\n",
    "    results_df = pd.concat(\n",
    "\n",
    "        [\n",
    "\n",
    "            results_df,\n",
    "\n",
    "            pd.DataFrame([result])\n",
    "\n",
    "        ],\n",
    "\n",
    "        ignore_index=True\n",
    "\n",
    "    )\n",
    "\n",
    "    results_df.to_csv(\n",
    "\n",
    "        result_file,\n",
    "\n",
    "        index=False\n",
    "\n",
    "    )\n",
    "\n",
    "    return results_df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8de164b4-9a8d-405c-8a81-db3ba94875ea",
   "metadata": {},
   "source": [
    "Stage 1 – Validate & Crash Recovery"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "f8ac7e1c-fce1-456d-9cd0-6a64ba58307c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Stage 1 : Validate Experiment\n",
    "# ==========================================================\n",
    "\n",
    "def validate_training(\n",
    "    model_name,\n",
    "    results_df\n",
    "):\n",
    "    \"\"\"\n",
    "    Check whether the model has already been trained.\n",
    "    \"\"\"\n",
    "\n",
    "    if is_completed(model_name, results_df):\n",
    "\n",
    "        print(f\"{model_name} already completed.\")\n",
    "\n",
    "        return False\n",
    "\n",
    "    return True"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d918725-2c92-456f-9f12-395b09c08668",
   "metadata": {},
   "source": [
    "Stage 2 – Select Dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "30df6a2d-ccc3-4353-aa9f-9f8c12aee56b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Stage 2 : Select Dataset\n",
    "# ==========================================================\n",
    "\n",
    "def select_training_data(\n",
    "    use_scaling,\n",
    "    X_train,\n",
    "    X_test,\n",
    "    X_train_scaled=None,\n",
    "    X_test_scaled=None\n",
    "):\n",
    "    \"\"\"\n",
    "    Return scaled or unscaled dataset.\n",
    "    \"\"\"\n",
    "\n",
    "    if use_scaling:\n",
    "\n",
    "        return X_train_scaled, X_test_scaled\n",
    "\n",
    "    return X_train, X_test"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a8607011-a26f-43dc-abd6-0a2de848d1c7",
   "metadata": {},
   "source": [
    "Stage 3 – Train Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "eed27725-de40-4375-bf22-d9d0afd2f706",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Stage 3 : Train Model\n",
    "# ==========================================================\n",
    "\n",
    "def fit_model(\n",
    "    model,\n",
    "    X_train,\n",
    "    y_train\n",
    "):\n",
    "    \"\"\"\n",
    "    Train the model and measure training time.\n",
    "    \"\"\"\n",
    "\n",
    "    start = time.perf_counter()\n",
    "\n",
    "    model.fit(\n",
    "        X_train,\n",
    "        y_train\n",
    "    )\n",
    "\n",
    "    train_time = time.perf_counter() - start\n",
    "\n",
    "    return model, train_time"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f64292fa-ecbf-4ecc-87e2-25684b5fb597",
   "metadata": {},
   "source": [
    "Stage 4 – Prediction"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "45317394-52db-48bd-bcab-6f6da4b987e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Stage 4 : Prediction\n",
    "# ==========================================================\n",
    "\n",
    "def make_predictions(\n",
    "    model,\n",
    "    X_test\n",
    "):\n",
    "    \"\"\"\n",
    "    Predict class labels and probabilities.\n",
    "    \"\"\"\n",
    "\n",
    "    start = time.perf_counter()\n",
    "\n",
    "    predictions = model.predict(\n",
    "        X_test\n",
    "    )\n",
    "\n",
    "    predict_time = time.perf_counter() - start\n",
    "\n",
    "    probabilities = None\n",
    "\n",
    "    if hasattr(model, \"predict_proba\"):\n",
    "\n",
    "        probabilities = model.predict_proba(\n",
    "            X_test\n",
    "        )\n",
    "\n",
    "    return predictions, probabilities, predict_time"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9624fe04-6dba-4424-acb5-a39c0b347fd6",
   "metadata": {},
   "source": [
    "Stage 5 – Feature Importance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "522be2ff-2ef6-4764-88b9-c893746304a4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==========================================================\n",
    "# Feature Importance\n",
    "# ==========================================================\n",
    "\n",
    "def extract_feature_importance(\n",
    "    model,\n",
    "    feature_names\n",
    "):\n",
    "    \"\"\"\n",
    "    Extract feature importance if available.\n",
    "    \"\"\"\n",
    "\n",
    "    if hasattr(model, \"feature_importances_\"):\n",
    "\n",
    "        importance = model.feature_importances_\n",
    "\n",
    "    elif hasattr(model, \"coef_\"):\n",
    "\n",
    "        importance = np.abs(model.coef_).mean(axis=0)\n",
    "\n",
    "    else:\n",
    "\n",
    "        return None\n",
    "\n",
    "    return pd.DataFrame({\n",
    "\n",
    "        \"Feature\": feature_names,\n",
    "\n",
    "        \"Importance\": importance\n",
    "\n",
    "    }).sort_values(\n",
    "\n",
    "        \"Importance\",\n",
    "\n",
    "        ascending=False\n",
    "\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "51d5e51d-fb29-4629-b1aa-c931644f4ee1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:ag_311]",
   "language": "python",
   "name": "conda-env-ag_311-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.15"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
